### ISSUE TITLE
Bug: Binding-Scripts get generated for Packaged UXMLs

### ISSUE THREAD

**Issue by siglocpp** [Eastrall/Rosalina#16]
I found an interesting bug, while generating some new UIs:
Rosalina somehow generated Binding Files for some pre-packaged uxmls inside of the unity-core. (see Screenshot).
![image](https://user-images.githubusercontent.com/5145659/174263534-9259ce98-5596-40ce-9d58-e91061d9852e.png)

I'm not quite sure how to reproduce this issue, but it happened to me now twice, after restarting unity.

I think, we need something like a Path-Filter on which uxmls to interprete, to prevent things like that from happening.
I suggest., that everything outside of the Assets-Folder should be ignored by default.

**Comment by Eastrall** [comment]
Indeed, since there is no filter on any folder here, all `.uxml` files are taken.

https://github.com/Eastrall/Rosalina/blob/50386ad6327350407a4bda1aaf3f2c368ed37de1/Editor/Scripts/RosalinaAssetProcessor.cs#L14-L16

This might happen when you re-import every assets in your project and thus, Unity's internal `UIDocuments`.
Thanks to your PR (#17) this might fix the issue. 😄

**Comment by Eastrall** [comment]
Closing this issue. Solved in PR #17
